[tool.poetry]
name = "fitness-food"
version = "0.1.0"
# ...

[tool.poetry.dependencies]  <-- ¡SOLO DEBE HABER UNA!
python = "^3.13"
Flask = "^3.0.0"
gunicorn = "^22.0.0"
# ... todas tus otras dependencias